reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    base_branches:
      - "master"
      - "dev"
  review_status: false

knowledge_base:
  jira:
    project_keys:
      - "KAN"

