reviews:
  auto_review: true
  auto_review_on:
    - "dev"

  # Hide the 'Review skipped' status message
  review_status: false

integrations:
  jira:
    enabled: true
    base_url: "${JIRA_BASE_URL}"
    email: "${JIRA_EMAIL}"
    api_token: "${JIRA_API_TOKEN}"
    project_keys:
      - "KAN"
    issue_patterns:
      - "[A-Z]+-[0-9]+"
